// 基础组件库统一出口（docs/design-system.md §2）
export { Button, type ButtonProps, type ButtonVariant, type ButtonSize } from './Button'
export { IconButton, type IconButtonProps, type IconButtonTone } from './IconButton'
export { Input, type InputProps } from './Input'
export { SearchInput, type SearchInputProps } from './SearchInput'
export { Textarea, type TextareaProps } from './Textarea'
export { Select, type SelectProps } from './Select'
export { RangeInput, type RangeInputProps } from './RangeInput'
export { Toggle, type ToggleProps, type ToggleTone } from './Toggle'
export { Stepper, type StepperProps } from './Stepper'
export { Checkbox, type CheckboxProps } from './Checkbox'
export { Radio, type RadioProps } from './Radio'
export { OptionCard, type OptionCardProps, type OptionCardSelection } from './OptionCard'
export { SegmentedTabs, type SegmentedTabsProps, type SegmentedOption } from './SegmentedTabs'
export { Badge, type BadgeTone } from './Badge'

export { Dialog, type DialogProps } from './Dialog'
export { ConfirmDialog, type ConfirmDialogProps } from './ConfirmDialog'
export { ModalSurface, type ModalSurfaceProps } from './ModalSurface'
export { Menu, type MenuProps, type MenuItem } from './Menu'
export { Scrim, type ScrimProps, type ScrimTone } from './Scrim'
export { ToastProvider, useToast, type ToastType } from './Toast'
export { Spinner, PageSpinner } from './Spinner'
export { Skeleton, type SkeletonProps } from './Skeleton'
export { EmptyState, type EmptyStateProps } from './EmptyState'
export { ProgressBar, type ProgressBarProps, type ProgressBarTone } from './ProgressBar'

export { PanelSurface, type PanelSurfaceProps, type PanelSurfaceVariant } from './PanelSurface'
export { PageContainer, type PageContainerProps, type PageContainerSize } from './PageContainer'
export { ListPageShell, type ListPageShellProps } from './ListPageShell'
export { CenteredShell } from './CenteredShell'
export { FadeIn, type FadeInProps } from './FadeIn'
export { SiteFooter } from './SiteFooter'
export { HeroHeader, type HeroHeaderProps } from './HeroHeader'
export { ActionBar, type ActionBarProps } from './ActionBar'
export { StatCard, type StatCardProps, type StatCardTone } from './StatCard'
export { Avatar, type AvatarProps } from './Avatar'
export { AchievementUnlocked, type AchievementUnlockedProps, type AchievementItem } from './AchievementUnlocked'
